plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mutz.fingerprintbypass'
    namespace 'com.mutz555.fingerprintbypass'
    compileSdk 33

    defaultConfig {
        applicationId "com.mutz.fingerprintbypass"
        minSdk 26
        targetSdk 33
    }

    packagingOptions {
        exclude "META-INF/*"
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
    google()
    mavenCentral()
}

dependencies {
    implementation files('libs/api-82.jar')
}